name: Deploy to Test

on:
  push:
    branches: 
      - test_*

jobs:

  deploy_container:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag discord_bot:test
    - name: stop and remote old container
      run: |
        docker stop discord_bot_test
        docker rm discord_bot_test
      continue-on-error: true
    - name: List images
      run: docker image ls
    - name: Run the Docker image
      run: docker run -d -e $discord_bot_token --name discord_bot_test discord_bot:test 
      env:
        discord_bot_token: ${{ secrets.test_discord_bot_token }}